import CPDLinear.BetweennessOrderUSC
import CPDLinear.ThinB

/-!
# Coalition-proof disclosure with thin-B correspondences

This file is the Lean handoff for the thin-B subsection of `tex/v5.tex`.
Every theorem is deliberately stated before it is proved, so the dependency
structure and the exact mathematical target are visible to the next proving
agent.  Do not replace `IsThinB` by the singleton correspondence
`{G.vbar μ}`: the upper envelope of a thin-B correspondence need not be
continuous.

The crown theorem uses `btw_order_usc`.  Its new geometric step is the
affine-span argument recorded in `BetweennessOrderUSC.lean`; no continuity of
the upper envelope is assumed.

For face restrictions and message-deleted auxiliary games, keep the ambient
correspondence and transport `HasCommonValueIntersections`.  Do not assert that
the restricted correspondence is a thin hull recomputed on the smaller
simplex: boundary cluster values can disappear under such a recomputation.
-/

open Set Topology
open scoped BigOperators Classical

namespace CPDLinear

variable {T Msg : Type*} [Fintype T] [Fintype Msg]

namespace DisclosureGame

variable {G : DisclosureGame T Msg}

/-- The game payoff correspondence is generated by a (possibly discontinuous)
bare payoff satisfying betweenness on the game's simplex. -/
def IsThinB (G : DisclosureGame T Msg) : Prop :=
  ∃ v : (T → ℝ) → ℝ,
    IsBetweenness G.Θ v ∧
      ∀ μ ∈ simplexOn G.Θ, G.V μ = thinB G.Θ v μ

/-- The correspondence-level property used by the game proofs.  It is stated
separately because, unlike the literal `IsThinB` representation, it is inherited
when the type space is restricted to a face and when messages are deleted. -/
def HasCommonValueIntersections (G : DisclosureGame T Msg) : Prop :=
  ∀ (n : ℕ) (a : Fin n → ℝ) (μs : Fin n → (T → ℝ)) (w : ℝ),
    (∀ i, 0 < a i) →
    (∑ i, a i = 1) →
    (∀ i, μs i ∈ simplexOn G.Θ) →
    (∀ i, w ∈ G.V (μs i)) →
    G.V (fun θ => ∑ i, a i * μs i θ) =
      {x | ∀ i, x ∈ G.V (μs i)}

/-- Thin-B implies the common-value intersection law. -/
theorem IsThinB.hasCommonValueIntersections (hthin : G.IsThinB) :
    G.HasCommonValueIntersections := by
  obtain ⟨v, hB, hV⟩ := hthin
  intro n a μs w hpos hsum hμ hw
  have hmix : (fun θ => ∑ i, a i * μs i θ) ∈ simplexOn G.Θ := by
    refine ⟨fun θ => Finset.sum_nonneg fun i _ =>
      mul_nonneg (le_of_lt (hpos i)) ((hμ i).1 θ), ?_, ?_⟩
    · calc
        ∑ θ, ∑ i, a i * μs i θ = ∑ i, ∑ θ, a i * μs i θ :=
          Finset.sum_comm
        _ = ∑ i, a i := by
          apply Finset.sum_congr rfl
          intro i _
          rw [← Finset.mul_sum, (hμ i).2.1, mul_one]
        _ = 1 := hsum
    · intro θ hθ
      apply Finset.sum_eq_zero
      intro i _
      rw [(hμ i).2.2 θ hθ, mul_zero]
  rw [hV _ hmix]
  have hw' : ∀ i, w ∈ thinB G.Θ v (μs i) := by
    intro i
    rw [← hV _ (hμ i)]
    exact hw i
  convert thinB_common_value G.Θ G.Θ_nonempty v hB n a μs w hpos hsum hμ hw' using 1
  ext x
  simp only [Set.mem_setOf_eq]
  constructor <;> intro hx i
  · rw [← hV _ (hμ i)]
    exact hx i
  · rw [hV _ (hμ i)]
    exact hx i

/-- The common-value intersection law passes to any face/message subgame that
keeps the ambient payoff correspondence on the smaller simplex.  This is the
transport lemma needed for every auxiliary game in the thin-B proof. -/
theorem HasCommonValueIntersections.of_subgame
    {H : DisclosureGame T Msg}
    (hcommon : G.HasCommonValueIntersections)
    (hΘ : H.Θ ⊆ G.Θ)
    (hV : ∀ μ ∈ simplexOn H.Θ, H.V μ = G.V μ) :
    H.HasCommonValueIntersections := by
  intro n a μs w hpos hsum hμ hw
  have hmix : (fun θ => ∑ i, a i * μs i θ) ∈ simplexOn H.Θ := by
    refine ⟨fun θ => Finset.sum_nonneg fun i _ =>
      mul_nonneg (le_of_lt (hpos i)) ((hμ i).1 θ), ?_, ?_⟩
    · calc
        ∑ θ, ∑ i, a i * μs i θ = ∑ i, ∑ θ, a i * μs i θ :=
          Finset.sum_comm
        _ = ∑ i, a i := by
          apply Finset.sum_congr rfl
          intro i _
          rw [← Finset.mul_sum, (hμ i).2.1, mul_one]
        _ = 1 := hsum
    · intro θ hθ
      apply Finset.sum_eq_zero
      intro i _
      rw [(hμ i).2.2 θ hθ, mul_zero]
  have hμG : ∀ i, μs i ∈ simplexOn G.Θ := fun i => simplexOn_mono hΘ (hμ i)
  have hwG : ∀ i, w ∈ G.V (μs i) := by
    intro i
    rw [← hV _ (hμ i)]
    exact hw i
  rw [hV _ hmix]
  convert hcommon n a μs w hpos hsum hμG hwG using 1
  ext x
  simp only [Set.mem_setOf_eq]
  constructor <;> intro hx i
  · rw [← hV _ (hμ i)]
    exact hx i
  · rw [hV _ (hμ i)]
    exact hx i

/-- The upper envelope of a thin-B game satisfies betweenness. -/
theorem IsThinB.betweenness (hthin : G.IsThinB) : G.Betweenness := by
  obtain ⟨v, hB, hV⟩ := hthin
  have hvbar {μ : T → ℝ} (hμ : μ ∈ simplexOn G.Θ) :
      G.vbar μ = thinBUpper G.Θ v μ := by
    rw [DisclosureGame.vbar, hV μ hμ,
      thinB_eq_Icc G.Θ G.Θ_nonempty v hB μ hμ]
    apply csSup_Icc
    obtain ⟨x, hx⟩ := G.V_nonempty μ hμ
    rw [hV μ hμ, thinB_eq_Icc G.Θ G.Θ_nonempty v hB μ hμ] at hx
    exact hx.1.trans hx.2
  intro μ hμ μ' hμ' l hl
  have hmix : (fun θ => l * μ θ + (1 - l) * μ' θ) ∈ simplexOn G.Θ := by
    refine ⟨?_, ?_, ?_⟩
    · intro θ
      exact add_nonneg (mul_nonneg (le_of_lt hl.1) (hμ.1 θ))
        (mul_nonneg (sub_nonneg.mpr (le_of_lt hl.2)) (hμ'.1 θ))
    · rw [Finset.sum_add_distrib, ← Finset.mul_sum, ← Finset.mul_sum,
        hμ.2.1, hμ'.2.1]
      ring
    · intro θ hθ
      simp only
      rw [hμ.2.2 θ hθ, hμ'.2.2 θ hθ]
      norm_num
  rw [hvbar hμ, hvbar hμ', hvbar hmix]
  exact thinBUpper_isBetweenness G.Θ G.Θ_nonempty v hB μ hμ μ' hμ' l hl

namespace Coalition

/-- Payoffs at which the fixed type set and fixed strategy of `K` still satisfy
the common-payoff condition.  All other coalition fields are unchanged. -/
def repayablePayoffs (K : Coalition G) : Set ℝ :=
  {w | ∀ m ∈ K.σ.evidence, w ∈ G.V (K.σ.coalitionBelief m)}

end Coalition

/-- **Exact coalition payoff set.**  Once a coalition strategy has one common
payoff, the set of all payoffs compatible with that same strategy is exactly
the correspondence value at the coalition prior. -/
theorem thinB_coalition_payoff_set
    (hcommon : G.HasCommonValueIntersections) (K : Coalition G) :
    K.repayablePayoffs = G.V (G.condPrior K.C) := by
  sorry

namespace Partition

/-- Every cell is paid at the upper endpoint of the correspondence evaluated
at its conditional prior. -/
def IsUpperNormalized (P : Partition G) : Prop :=
  ∀ t, P.w t = G.vbar (G.condPrior (P.C t))

end Partition

/-- **Upper-normalized PBE.**  The common-value intersection law is the only
extra correspondence property needed to normalize an existing PBE partition.
This formulation applies directly to restricted and message-deleted auxiliary
games once the law has been transported to them. -/
theorem exists_upperNormalizedPBE
    (hcommon : G.HasCommonValueIntersections) :
    ∃ P : Partition G,
      P.IsPBEPartition ∧ StrictAnti P.w ∧ P.IsUpperNormalized := by
  sorry

/-- Exact wrapper for `prop:thinB-upper-pbe`: every face/message subgame that
keeps the ambient thin-B values admits an upper-normalized PBE partition. -/
theorem thinB_upperNormalizedPBE_subgame
    (hthin : G.IsThinB) {H : DisclosureGame T Msg}
    (hΘ : H.Θ ⊆ G.Θ)
    (hV : ∀ μ ∈ simplexOn H.Θ, H.V μ = G.V μ) :
    ∃ P : Partition H,
      P.IsPBEPartition ∧ StrictAnti P.w ∧ P.IsUpperNormalized := by
  sorry

/-- **Thin-B attainment.**  The largest coalition payoff on a residual face is
the largest upper-envelope pooling value over relative message preimages. -/
theorem thinB_attained (hthin : G.IsThinB)
    {R : Finset T} (hne : R.Nonempty) (hsub : R ⊆ G.Θ) :
    IsGreatest (G.restrict R hne hsub).coalitionPayoffs (G.vstar R) := by
  sorry

/-- **Thin-B merging.**  If a payoff-maximal coalition is followed by a
strictly better residual coalition, their evidence preimage is the union of
their type sets and the upper value of the union is the old maximum. -/
theorem thinB_merging (hthin : G.IsThinB)
    {R : Finset T} (hne : R.Nonempty) (hsub : R ⊆ G.Θ)
    (K : Coalition (G.restrict R hne hsub))
    (hmax : IsGreatest (G.restrict R hne hsub).coalitionPayoffs K.w)
    (hne' : (R \ K.C).Nonempty)
    (K' : Coalition
      (G.restrict (R \ K.C) hne' (Finset.sdiff_subset.trans hsub)))
    (hgt : K.w < K'.w) :
    G.preimageSet R (K.σ.evidence ∪ K'.σ.evidence) = K.C ∪ K'.C ∧
      G.vbar (G.condPrior (K.C ∪ K'.C)) = K.w := by
  sorry

/-- **Thin-B existence.** Every thin-B disclosure game admits a
coalition-proof PBE.  The upper envelope is upper semicontinuous and satisfies
betweenness, so `btw_order_usc` supplies the rank used in the greedy
construction. -/
theorem thinB_existence (hthin : G.IsThinB) :
    ∃ P : Partition G, P.IsCPPBEPartition := by
  sorry

end DisclosureGame

end CPDLinear
