import CPDLinear.BetweennessOrder
import CPDLinear.ThinB

/-!
# Coalition-proof disclosure with thin-B correspondences

This file is the Lean handoff for the thin-B subsection of `tex/v5.tex`.
Every theorem is deliberately stated before it is proved, so the dependency
structure and the exact mathematical target are visible to the next proving
agent.  Do not replace `IsThinB` by the singleton correspondence
`{G.vbar μ}`: the upper envelope of a thin-B correspondence need not be
continuous.

The unconditional existence target remains a conjecture.  The proved-on-paper
target `thinB_existence_of_continuousUpper` adds exactly the continuity needed
by the existing level-set ranking construction.  A proof of `thinB_existence`
must first replace that use of continuity or use a different finite selection
argument.
-/

open Set Topology
open scoped BigOperators Classical

namespace CPDLinear

variable {T Msg : Type*} [Fintype T] [Fintype Msg]

namespace DisclosureGame

variable {G : DisclosureGame T Msg}

/-- The game payoff correspondence is generated by a (possibly discontinuous)
bare payoff satisfying betweenness on the game's simplex. -/
def IsThinB (G : DisclosureGame T Msg) : Prop :=
  ∃ v : (T → ℝ) → ℝ,
    IsBetweenness G.Θ v ∧
      ∀ μ ∈ simplexOn G.Θ, G.V μ = thinB G.Θ v μ

/-- The correspondence-level property used by the game proofs.  It is stated
separately because, unlike the literal `IsThinB` representation, it is inherited
when the type space is restricted to a face and when messages are deleted. -/
def HasCommonValueIntersections (G : DisclosureGame T Msg) : Prop :=
  ∀ (n : ℕ) (a : Fin n → ℝ) (μs : Fin n → (T → ℝ)) (w : ℝ),
    (∀ i, 0 < a i) →
    (∑ i, a i = 1) →
    (∀ i, μs i ∈ simplexOn G.Θ) →
    (∀ i, w ∈ G.V (μs i)) →
    G.V (fun θ => ∑ i, a i * μs i θ) =
      {x | ∀ i, x ∈ G.V (μs i)}

/-- Thin-B implies the common-value intersection law. -/
theorem IsThinB.hasCommonValueIntersections (hthin : G.IsThinB) :
    G.HasCommonValueIntersections := by
  sorry

/-- The upper envelope of a thin-B game satisfies betweenness. -/
theorem IsThinB.betweenness (hthin : G.IsThinB) : G.Betweenness := by
  sorry

namespace Coalition

/-- Payoffs at which the fixed type set and fixed strategy of `K` still satisfy
the common-payoff condition.  All other coalition fields are unchanged. -/
def repayablePayoffs (K : Coalition G) : Set ℝ :=
  {w | ∀ m ∈ K.σ.evidence, w ∈ G.V (K.σ.coalitionBelief m)}

end Coalition

/-- **Exact coalition payoff set.**  Once a coalition strategy has one common
payoff, the set of all payoffs compatible with that same strategy is exactly
the correspondence value at the coalition prior. -/
theorem thinB_coalition_payoff_set
    (hcommon : G.HasCommonValueIntersections) (K : Coalition G) :
    K.repayablePayoffs = G.V (G.condPrior K.C) := by
  sorry

namespace Partition

/-- Every cell is paid at the upper endpoint of the correspondence evaluated
at its conditional prior. -/
def IsUpperNormalized (P : Partition G) : Prop :=
  ∀ t, P.w t = G.vbar (G.condPrior (P.C t))

end Partition

/-- **Upper-normalized PBE.**  The common-value intersection law is the only
extra correspondence property needed to normalize an existing PBE partition.
This formulation applies directly to restricted and message-deleted auxiliary
games once the law has been transported to them. -/
theorem exists_upperNormalizedPBE
    (hcommon : G.HasCommonValueIntersections) :
    ∃ P : Partition G,
      P.IsPBEPartition ∧ StrictAnti P.w ∧ P.IsUpperNormalized := by
  sorry

/-- **Thin-B attainment.**  The largest coalition payoff on a residual face is
the largest upper-envelope pooling value over relative message preimages. -/
theorem thinB_attained (hthin : G.IsThinB)
    {R : Finset T} (hne : R.Nonempty) (hsub : R ⊆ G.Θ) :
    IsGreatest (G.restrict R hne hsub).coalitionPayoffs (G.vstar R) := by
  sorry

/-- **Thin-B merging.**  If a payoff-maximal coalition is followed by a
strictly better residual coalition, their evidence preimage is the union of
their type sets and the upper value of the union is the old maximum. -/
theorem thinB_merging (hthin : G.IsThinB)
    {R : Finset T} (hne : R.Nonempty) (hsub : R ⊆ G.Θ)
    (K : Coalition (G.restrict R hne hsub))
    (hmax : IsGreatest (G.restrict R hne hsub).coalitionPayoffs K.w)
    (hne' : (R \ K.C).Nonempty)
    (K' : Coalition
      (G.restrict (R \ K.C) hne' (Finset.sdiff_subset.trans hsub)))
    (hgt : K.w < K'.w) :
    G.preimageSet R (K.σ.evidence ∪ K'.σ.evidence) = K.C ∪ K'.C ∧
      G.vbar (G.condPrior (K.C ∪ K'.C)) = K.w := by
  sorry

/-- The crown theorem with the hypothesis currently required by the verified
level-set ranking construction. -/
theorem thinB_existence_of_continuousUpper (hthin : G.IsThinB)
    (hcont : ContinuousOn G.vbar (simplexOn G.Θ)) :
    ∃ P : Partition G, P.IsCPPBEPartition := by
  sorry

/-- **Open crown target.**  This is Conjecture `conj:thinB-cppbe` in
`tex/v5.tex`.  Upper semicontinuity does not justify the continuity step in
`btw_order_aux`; proving this declaration requires a new ranking theorem for
boundary jumps or a different selection argument. -/
theorem thinB_existence (hthin : G.IsThinB) :
    ∃ P : Partition G, P.IsCPPBEPartition := by
  sorry

end DisclosureGame

end CPDLinear
