import CPDLinear.Game

/-!
# Thin-B correspondences  (extension: `tex/extension/thin-B.tex`)

A single-valued payoff `v : (T → ℝ) → ℝ`, **not assumed continuous**, satisfies
betweenness (B) on `Δ Θ` if every mixture's value lies between the endpoint
values (`IsBetweenness`).  The **thin-B correspondence** generated by `v` is
`thinB Θ v μ := Conv Lᵥ(μ)`, where `Lᵥ(μ)` is the set of subsequential limit
values of `v` along sequences in `Δ Θ` approaching `μ` (`clusterValues`).

This module is the prep work for later replacing B by thin-B inside a
`DisclosureGame`.  The first goal (`thinB_A4`) is that a thin-B correspondence
satisfies **A4**: it is upper hemicontinuous with non-empty compact interval
values — exactly the four value/regularity fields required by `DisclosureGame`
(`V_nonempty`, `V_isCompact`, `V_ordConnected`, `V_uhc`).

It imports only `CPDLinear.Game` (which imports only `CPDLinear.Simplex` →
`Mathlib`), so it is **axiom-free**: it does not transitively depend on
`CPDLinear.kakutani`.

The proofs are left as `sorry` for Aristotle.  Proof outline (see the `.tex`):

* **Step 1 — `IsBetweenness.bddOn_simplex`.** Iterated B (a Jensen-type
  induction over convex combinations) bounds `v` on `Δ Θ` by its values at the
  vertices `δθ`: `v μ ∈ [minθ v(δθ), maxθ v(δθ)]`.  Hence every `Lᵥ(μ) ⊆ [a,b]`.
* **Step 2 — values.** `Lᵥ(μ)` is closed (diagonal argument) and, being
  bounded, compact and non-empty (the constant sequence gives `v μ ∈ Lᵥ(μ)`).
  Its convex hull is the compact interval `[v̲(μ), v̄(μ)]`, with
  `v̲(μ) = min Lᵥ(μ)`, `v̄(μ) = max Lᵥ(μ)`.
* **Step 3 — envelopes.** `v̄ = sup Lᵥ` is upper semicontinuous and
  `v̲ = inf Lᵥ` is lower semicontinuous on `Δ Θ`.
* **Step 4 — UHC.** For open `U ⊇ [v̲(μ), v̄(μ)]`, an `ε`-fattening plus Step 3
  gives a neighbourhood on which `[v̲(·), v̄(·)] ⊆ U`.
-/

open Set Filter Topology

namespace CPDLinear

variable {T : Type*} [Fintype T]

/-- **Betweenness (B)** for a bare single-valued payoff `v` on `Δ Θ`: for all
`μ, μ' ∈ Δ Θ` and `l ∈ (0,1)`, the value `v (l·μ + (1-l)·μ')` lies between
`v μ` and `v μ'`.  Continuity of `v` is **not** assumed. -/
def IsBetweenness (Θ : Finset T) (v : (T → ℝ) → ℝ) : Prop :=
  ∀ μ ∈ simplexOn Θ, ∀ μ' ∈ simplexOn Θ, ∀ l : ℝ, l ∈ Set.Ioo (0 : ℝ) 1 →
    min (v μ) (v μ') ≤ v (fun θ => l * μ θ + (1 - l) * μ' θ) ∧
      v (fun θ => l * μ θ + (1 - l) * μ' θ) ≤ max (v μ) (v μ')

/-- **`Lᵥ(μ)`** — the set of subsequential limit values of `v` along sequences
in `Δ Θ` approaching `μ`:
`{ w | ∃ (μₙ) ⊆ Δ Θ, μₙ → μ and v(μₙ) → w }`.  The constant sequence
`μₙ ≡ μ` shows `v μ ∈ clusterValues Θ v μ`. -/
def clusterValues (Θ : Finset T) (v : (T → ℝ) → ℝ) (μ : T → ℝ) : Set ℝ :=
  {w | ∃ x : ℕ → (T → ℝ), (∀ n, x n ∈ simplexOn Θ) ∧
        Tendsto x atTop (𝓝 μ) ∧ Tendsto (fun n => v (x n)) atTop (𝓝 w)}

/-- **Thin-B correspondence** generated by `v`: `V(μ) := Conv Lᵥ(μ)`. -/
noncomputable def thinB (Θ : Finset T) (v : (T → ℝ) → ℝ) : (T → ℝ) → Set ℝ :=
  fun μ => convexHull ℝ (clusterValues Θ v μ)

/-! ## Goal 1: a thin-B correspondence satisfies A4 -/

/-- **Keystone (Step 1).** A betweenness payoff is bounded on `Δ Θ` by its
values at the vertices `δθ`; hence `clusterValues Θ v μ ⊆ [a, b]` for all `μ`.
This is the fact that makes the thin-B values compact. -/
lemma IsBetweenness.bddOn_simplex (Θ : Finset T) (hΘ : Θ.Nonempty)
    {v : (T → ℝ) → ℝ} (hB : IsBetweenness Θ v) :
    ∃ a b : ℝ, ∀ μ ∈ simplexOn Θ, v μ ∈ Set.Icc a b := by
  sorry

/-- **`thinB_A4`.** If `v` satisfies betweenness on `Δ Θ`, then its thin-B
correspondence `thinB Θ v` satisfies **A4**: non-empty, compact, order-connected
(interval) values on `Δ Θ`, and upper hemicontinuity on `Δ Θ`.  These are exactly
the payoff-correspondence fields of a `DisclosureGame`. -/
theorem thinB_A4 (Θ : Finset T) (hΘ : Θ.Nonempty) (v : (T → ℝ) → ℝ)
    (hB : IsBetweenness Θ v) :
    (∀ μ ∈ simplexOn Θ, (thinB Θ v μ).Nonempty) ∧
      (∀ μ ∈ simplexOn Θ, IsCompact (thinB Θ v μ)) ∧
      (∀ μ ∈ simplexOn Θ, (thinB Θ v μ).OrdConnected) ∧
      UpperHemicontinuousOn (thinB Θ v) (simplexOn Θ) := by
  sorry

end CPDLinear
