import CPDLinear.BetweennessOrderUSC
import CPDLinear.ThinB

/-!
# Coalition-proof disclosure with thin-B correspondences

This file is the Lean handoff for the thin-B subsection of `tex/v5.tex`.
Every theorem is deliberately stated before it is proved, so the dependency
structure and the exact mathematical target are visible to the next proving
agent.  Do not replace `IsThinB` by the singleton correspondence
`{G.vbar μ}`: the upper envelope of a thin-B correspondence need not be
continuous.

The crown theorem uses `btw_order_usc`.  Its new geometric step is the
affine-span argument recorded in `BetweennessOrderUSC.lean`; no continuity of
the upper envelope is assumed.

For face restrictions and message-deleted auxiliary games, keep the ambient
correspondence and transport `HasCommonValueIntersections`.  Do not assert that
the restricted correspondence is a thin hull recomputed on the smaller
simplex: boundary cluster values can disappear under such a recomputation.
-/

open Set Topology
open scoped BigOperators Classical

namespace CPDLinear

variable {T Msg : Type*} [Fintype T] [Fintype Msg]

namespace DisclosureGame

variable {G : DisclosureGame T Msg}

/-- The game payoff correspondence is generated by a (possibly discontinuous)
bare payoff satisfying betweenness on the game's simplex. -/
def IsThinB (G : DisclosureGame T Msg) : Prop :=
  ∃ v : (T → ℝ) → ℝ,
    IsBetweenness G.Θ v ∧
      ∀ μ ∈ simplexOn G.Θ, G.V μ = thinB G.Θ v μ

/-- The correspondence-level property used by the game proofs.  It is stated
separately because, unlike the literal `IsThinB` representation, it is inherited
when the type space is restricted to a face and when messages are deleted. -/
def HasCommonValueIntersections (G : DisclosureGame T Msg) : Prop :=
  ∀ (n : ℕ) (a : Fin n → ℝ) (μs : Fin n → (T → ℝ)) (w : ℝ),
    (∀ i, 0 < a i) →
    (∑ i, a i = 1) →
    (∀ i, μs i ∈ simplexOn G.Θ) →
    (∀ i, w ∈ G.V (μs i)) →
    G.V (fun θ => ∑ i, a i * μs i θ) =
      {x | ∀ i, x ∈ G.V (μs i)}

/-- Thin-B implies the common-value intersection law. -/
theorem IsThinB.hasCommonValueIntersections (hthin : G.IsThinB) :
    G.HasCommonValueIntersections := by
  obtain ⟨v, hB, hV⟩ := hthin
  intro n a μs w hpos hsum hμ hw
  have hmix : (fun θ => ∑ i, a i * μs i θ) ∈ simplexOn G.Θ := by
    refine ⟨fun θ => Finset.sum_nonneg fun i _ =>
      mul_nonneg (le_of_lt (hpos i)) ((hμ i).1 θ), ?_, ?_⟩
    · calc
        ∑ θ, ∑ i, a i * μs i θ = ∑ i, ∑ θ, a i * μs i θ :=
          Finset.sum_comm
        _ = ∑ i, a i := by
          apply Finset.sum_congr rfl
          intro i _
          rw [← Finset.mul_sum, (hμ i).2.1, mul_one]
        _ = 1 := hsum
    · intro θ hθ
      apply Finset.sum_eq_zero
      intro i _
      rw [(hμ i).2.2 θ hθ, mul_zero]
  rw [hV _ hmix]
  have hw' : ∀ i, w ∈ thinB G.Θ v (μs i) := by
    intro i
    rw [← hV _ (hμ i)]
    exact hw i
  convert thinB_common_value G.Θ G.Θ_nonempty v hB n a μs w hpos hsum hμ hw' using 1
  ext x
  simp only [Set.mem_setOf_eq]
  constructor <;> intro hx i
  · rw [← hV _ (hμ i)]
    exact hx i
  · rw [hV _ (hμ i)]
    exact hx i

/-- The common-value intersection law passes to any face/message subgame that
keeps the ambient payoff correspondence on the smaller simplex.  This is the
transport lemma needed for every auxiliary game in the thin-B proof. -/
theorem HasCommonValueIntersections.of_subgame
    {H : DisclosureGame T Msg}
    (hcommon : G.HasCommonValueIntersections)
    (hΘ : H.Θ ⊆ G.Θ)
    (hV : ∀ μ ∈ simplexOn H.Θ, H.V μ = G.V μ) :
    H.HasCommonValueIntersections := by
  intro n a μs w hpos hsum hμ hw
  have hmix : (fun θ => ∑ i, a i * μs i θ) ∈ simplexOn H.Θ := by
    refine ⟨fun θ => Finset.sum_nonneg fun i _ =>
      mul_nonneg (le_of_lt (hpos i)) ((hμ i).1 θ), ?_, ?_⟩
    · calc
        ∑ θ, ∑ i, a i * μs i θ = ∑ i, ∑ θ, a i * μs i θ :=
          Finset.sum_comm
        _ = ∑ i, a i := by
          apply Finset.sum_congr rfl
          intro i _
          rw [← Finset.mul_sum, (hμ i).2.1, mul_one]
        _ = 1 := hsum
    · intro θ hθ
      apply Finset.sum_eq_zero
      intro i _
      rw [(hμ i).2.2 θ hθ, mul_zero]
  have hμG : ∀ i, μs i ∈ simplexOn G.Θ := fun i => simplexOn_mono hΘ (hμ i)
  have hwG : ∀ i, w ∈ G.V (μs i) := by
    intro i
    rw [← hV _ (hμ i)]
    exact hw i
  rw [hV _ hmix]
  convert hcommon n a μs w hpos hsum hμG hwG using 1
  ext x
  simp only [Set.mem_setOf_eq]
  constructor <;> intro hx i
  · rw [← hV _ (hμ i)]
    exact hx i
  · rw [hV _ (hμ i)]
    exact hx i

/-- The upper envelope of a thin-B game satisfies betweenness. -/
theorem IsThinB.betweenness (hthin : G.IsThinB) : G.Betweenness := by
  obtain ⟨v, hB, hV⟩ := hthin
  have hvbar {μ : T → ℝ} (hμ : μ ∈ simplexOn G.Θ) :
      G.vbar μ = thinBUpper G.Θ v μ := by
    rw [DisclosureGame.vbar, hV μ hμ,
      thinB_eq_Icc G.Θ G.Θ_nonempty v hB μ hμ]
    apply csSup_Icc
    obtain ⟨x, hx⟩ := G.V_nonempty μ hμ
    rw [hV μ hμ, thinB_eq_Icc G.Θ G.Θ_nonempty v hB μ hμ] at hx
    exact hx.1.trans hx.2
  intro μ hμ μ' hμ' l hl
  have hmix : (fun θ => l * μ θ + (1 - l) * μ' θ) ∈ simplexOn G.Θ := by
    refine ⟨?_, ?_, ?_⟩
    · intro θ
      exact add_nonneg (mul_nonneg (le_of_lt hl.1) (hμ.1 θ))
        (mul_nonneg (sub_nonneg.mpr (le_of_lt hl.2)) (hμ'.1 θ))
    · rw [Finset.sum_add_distrib, ← Finset.mul_sum, ← Finset.mul_sum,
        hμ.2.1, hμ'.2.1]
      ring
    · intro θ hθ
      simp only
      rw [hμ.2.2 θ hθ, hμ'.2.2 θ hθ]
      norm_num
  rw [hvbar hμ, hvbar hμ', hvbar hmix]
  exact thinBUpper_isBetweenness G.Θ G.Θ_nonempty v hB μ hμ μ' hμ' l hl

namespace Coalition

/-- Payoffs at which the fixed type set and fixed strategy of `K` still satisfy
the common-payoff condition.  All other coalition fields are unchanged. -/
def repayablePayoffs (K : Coalition G) : Set ℝ :=
  {w | ∀ m ∈ K.σ.evidence, w ∈ G.V (K.σ.coalitionBelief m)}

end Coalition

private lemma thinB_bayes (s : Strategy G) :
    (∀ θ, G.μ0 θ = ∑ m ∈ Finset.univ.filter (fun m => m ∈ s.evidence),
      s.onPathProb m * s.belief m θ) ∧
    (∑ m ∈ Finset.univ.filter (fun m => m ∈ s.evidence), s.onPathProb m = 1) := by
  refine ⟨fun θ => ?_, ?_⟩
  · by_cases hθ : θ ∈ G.Θ <;> simp_all +decide [Strategy.belief]
    · rw [Finset.sum_congr rfl fun x hx => by
        rw [mul_div_cancel₀ _ (ne_of_gt (s.onPathProb_pos_iff_mem_evidence x |>.2
          (by simpa using hx)))]]
      have hsum : ∑ m ∈ Finset.univ.filter (fun m => m ∈ s.evidence), s.σ θ m = 1 := by
        have hall : ∑ m ∈ Finset.univ, s.σ θ m = 1 := (s.mem θ hθ).2.1
        rw [← hall, ← Finset.sum_subset (Finset.subset_univ _)]
        simp +contextual [Strategy.evidence, Strategy.msgSupport]
        exact fun m hm => le_antisymm (hm θ hθ) ((s.mem θ hθ).1 m)
      rw [← Finset.mul_sum, hsum, mul_one]
    · have hz := G.μ0_mem.2.2 θ hθ
      aesop
  · unfold Strategy.onPathProb
    rw [Finset.sum_comm]
    have hsum : ∀ θ ∈ G.Θ,
        ∑ m ∈ Finset.univ.filter (fun m => m ∈ s.evidence), s.σ θ m = 1 := by
      intro θ hθ
      have hall : ∑ m ∈ Finset.univ, s.σ θ m = 1 := (s.mem θ hθ).2.1
      rw [← hall, ← Finset.sum_subset (Finset.subset_univ _)]
      simp +contextual [Strategy.evidence, Strategy.msgSupport]
      exact fun m hm => le_antisymm (hm θ hθ) ((s.mem θ hθ).1 m)
    convert G.priorMeasure_self using 1
    exact Finset.sum_congr rfl fun θ hθ => by rw [← Finset.mul_sum, hsum θ hθ, mul_one]

private lemma thinB_condPrior_decomp (K : Coalition G) :
    G.condPrior K.C = fun θ =>
      ∑ m ∈ Finset.univ.filter (fun m => m ∈ K.σ.evidence),
        K.σ.onPathProb m * K.σ.coalitionBelief m θ := by
  funext θ
  convert (thinB_bayes K.σ).1 θ using 1
  refine Finset.sum_congr rfl fun m hm => ?_
  simp +decide [Strategy.coalitionBelief, Strategy.belief] at hm ⊢
  by_cases hθ : θ ∈ K.C <;> simp +decide [hθ, zeroExt]
  · convert Or.inl rfl using 1
  · rw [DisclosureGame.condPrior_of_not_mem] <;> simp +decide [hθ]

private lemma thinB_coalitionBelief_mem (K : Coalition G)
    {m : Msg} (hm : m ∈ K.σ.evidence) :
    K.σ.coalitionBelief m ∈ simplexOn G.Θ := by
  convert zeroExt_mem_simplex K.C_subset _
  exact K.σ.belief_mem_simplex hm

/-- **Exact coalition payoff set.**  Once a coalition strategy has one common
payoff, the set of all payoffs compatible with that same strategy is exactly
the correspondence value at the coalition prior. -/
theorem thinB_coalition_payoff_set
    (hcommon : G.HasCommonValueIntersections) (K : Coalition G) :
    K.repayablePayoffs = G.V (G.condPrior K.C) := by
  -- The condPrior is a convex combination of coalition beliefs
  rw [thinB_condPrior_decomp K]
  -- Define the finset of evidence messages
  let ev : Finset Msg := Finset.univ.filter (fun m => m ∈ K.σ.evidence)
  -- The sum over the filtered finset can be reindexed to Fin n
  let n := ev.card
  -- Create an equivalence between Fin n and the evidence finset
  let eqv : Fin n ≃ ev := (Finset.equivFin ev).symm
  -- Define the weight function and belief function indexed by Fin n
  let a : Fin n → ℝ := fun i => K.σ.onPathProb (eqv i).val
  let μs : Fin n → (T → ℝ) := fun i => K.σ.coalitionBelief (eqv i).val
  -- Reindex the sum
  have hsum_eq : ∀ θ, ∑ m with m ∈ K.σ.evidence, K.σ.onPathProb m * K.σ.coalitionBelief m θ =
      ∑ i : Fin n, a i * μs i θ := by
    intro θ
    simp only [a, μs]
    let eqv' : Fin n ≃ ev := Finset.equivFin ev |>.symm
    rw [show (Finset.univ.filter (fun m => m ∈ K.σ.evidence) : Finset Msg) = ev from rfl]
    let g : ↥ev → ℝ := fun m => K.σ.onPathProb m.val * K.σ.coalitionBelief m.val θ
    rw [eqv.sum_comp g]
    rw [← Finset.sum_coe_sort]
  simp_all +decide
  -- Now apply HasCommonValueIntersections
  have hev : ev = Finset.univ.filter (fun m => m ∈ K.σ.evidence) := rfl
  have mem_ev_to_mem_evidence : ∀ m : Msg, m ∈ ev → m ∈ K.σ.evidence := by
    intro m hm
    simp [hev] at hm
    exact hm
  rw [hcommon n a μs K.w
      (fun i => (K.σ.onPathProb_pos_iff_mem_evidence _).mpr (mem_ev_to_mem_evidence _ (eqv i).property))
      (by
        have h := thinB_bayes K.σ |>.2
        -- h : ∑ m ∈ Finset.univ.filter (fun m => m ∈ K.σ.evidence), K.σ.onPathProb m = 1
        simp only [a]
        convert h using 1
        symm
        rw [eqv.sum_comp (fun m : ↥ev => K.σ.onPathProb m.val)]
        rw [← Finset.sum_coe_sort])
      (fun i => thinB_coalitionBelief_mem K (mem_ev_to_mem_evidence _ (eqv i).property))
      (fun i => K.payoff (eqv i).val (mem_ev_to_mem_evidence _ (eqv i).property))]
  -- Now prove the set equality
  have heq : K.repayablePayoffs = {w | ∀ m ∈ K.σ.evidence, w ∈ G.V (K.σ.coalitionBelief m)} := rfl
  rw [heq]
  apply Set.ext
  intro x
  constructor
  · intro hx i
    exact hx (eqv i).val (mem_ev_to_mem_evidence _ (eqv i).property)
  · intro hx m hm
    have hm' : m ∈ ev := by simp [hev]; exact hm
    let i := eqv.symm (Subtype.mk m hm')
    have heqv : eqv i = Subtype.mk m hm' := eqv.apply_symm_apply (Subtype.mk m hm')
    have hval : (eqv i).val = m := by rw [heqv]
    have := hx i
    simp only [μs] at this
    rw [hval] at this
    exact this

namespace Partition

/-- Every cell is paid at the upper endpoint of the correspondence evaluated
at its conditional prior. -/
def IsUpperNormalized (P : Partition G) : Prop :=
  ∀ t, P.w t = G.vbar (G.condPrior (P.C t))

end Partition

/-- **Upper-normalized PBE.**  The common-value intersection law is the only
extra correspondence property needed to normalize an existing PBE partition.
This formulation applies directly to restricted and message-deleted auxiliary
games once the law has been transported to them. -/
theorem exists_upperNormalizedPBE
    (hcommon : G.HasCommonValueIntersections) :
    ∃ P : Partition G,
      P.IsPBEPartition ∧ StrictAnti P.w ∧ P.IsUpperNormalized := by
  sorry

/-- Exact wrapper for `prop:thinB-upper-pbe`: every face/message subgame that
keeps the ambient thin-B values admits an upper-normalized PBE partition. -/
theorem thinB_upperNormalizedPBE_subgame
    (hthin : G.IsThinB) {H : DisclosureGame T Msg}
    (hΘ : H.Θ ⊆ G.Θ)
    (hV : ∀ μ ∈ simplexOn H.Θ, H.V μ = G.V μ) :
    ∃ P : Partition H,
      P.IsPBEPartition ∧ StrictAnti P.w ∧ P.IsUpperNormalized := by
  apply exists_upperNormalizedPBE
  exact (hthin.hasCommonValueIntersections).of_subgame hΘ hV

/-- **Thin-B attainment.**  The largest coalition payoff on a residual face is
the largest upper-envelope pooling value over relative message preimages. -/
theorem thinB_attained (hthin : G.IsThinB)
    {R : Finset T} (hne : R.Nonempty) (hsub : R ⊆ G.Θ) :
    IsGreatest (G.restrict R hne hsub).coalitionPayoffs (G.vstar R) := by
  sorry

/-- **Thin-B merging.**  If a payoff-maximal coalition is followed by a
strictly better residual coalition, their evidence preimage is the union of
their type sets and the upper value of the union is the old maximum. -/
theorem thinB_merging (hthin : G.IsThinB)
    {R : Finset T} (hne : R.Nonempty) (hsub : R ⊆ G.Θ)
    (K : Coalition (G.restrict R hne hsub))
    (hmax : IsGreatest (G.restrict R hne hsub).coalitionPayoffs K.w)
    (hne' : (R \ K.C).Nonempty)
    (K' : Coalition
      (G.restrict (R \ K.C) hne' (Finset.sdiff_subset.trans hsub)))
    (hgt : K.w < K'.w) :
    G.preimageSet R (K.σ.evidence ∪ K'.σ.evidence) = K.C ∪ K'.C ∧
      G.vbar (G.condPrior (K.C ∪ K'.C)) = K.w := by
  sorry

/-- **Thin-B existence.** Every thin-B disclosure game admits a
coalition-proof PBE.  The upper envelope is upper semicontinuous and satisfies
betweenness, so `btw_order_usc` supplies the rank used in the greedy
construction. -/
theorem thinB_existence (hthin : G.IsThinB) :
    ∃ P : Partition G, P.IsCPPBEPartition := by
  sorry

end DisclosureGame

end CPDLinear
